# -*- coding: utf-8 -*-
"""anime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwJb1_8QjbIvOSElGqKC8x-H_iecRHnA

# Análise de Dados em Séries de Anime:  Gêneros, Avaliações e Tendências

### Equipe:
* Maria Júlia Silva Fonseca Guedes Nobre
* Vinícius José Aragão de Almeida Barrozo

### Objetivos:
- Identificar os gêneros mais frequentes.
- Avaliar quais gêneros têm as melhores (e piores) notas médias.
- Descobrir as combinações de gêneros mais comuns.
- Analisar a relação entre popularidade e avaliação.
- Testar um modelo preditivo baseado nas avaliações.

# 1. Inicialização da Database

Download dos arquivos via API do kaggle e criação do dataframe inicial
"""

import kagglehub
import polars as pl

# Baixar e carregar o dataset
path = kagglehub.dataset_download("hernan4444/anime-recommendation-database-2020")
anime_polars = pl.read_csv(path + "/anime.csv", null_values="Unknown")

anime_polars.head()

"""# 2. Pré Processamento

###  2.1. Remover valores nulos em colunas importantes (`Genres` e `Scores`)
"""

df_clean = anime_polars.filter(
    (anime_polars['Genres'].is_not_null()) & (anime_polars['Score'].is_not_null())
)

print(df_clean)

"""### 2.2. Separar a coluna `Genres` em uma lista"""

df_clean = df_clean.with_columns(
    pl.col('Genres')
    .str.replace("Hentai", "Adult Content")
    .str.split(", ")                       # converte para lista
)

print(df_clean)

"""###  2.3. Criar coluna com combinação ordenada dos gêneros"""

def process_genres(genres):
    try:
        if genres is not None and len(genres) > 0:
            return ", ".join(sorted(genres))
        else:
            return ""
    except (TypeError, AttributeError):
        return ""

df_clean = df_clean.with_columns(
    pl.col('Genres').map_elements(process_genres, return_dtype=pl.Utf8).alias('Genres_combination')
)
# download em formato json da database polars
df_clean.write_json('df_clean.json')

"""# 3. Análises Exploratórias"""

import plotly.express as px

# Explodir para análise individual de gêneros
df_exploded = df_clean.explode('Genres')

print(df_clean)

"""### 3.1. Gêneros mais frequentes

"""

genero_freq = (
    df_exploded.group_by('Genres')
    .len()
    .sort('len', descending=True)
    .rename({'len': 'Frequencia'})
)

px.bar(genero_freq.to_pandas(), x='Genres', y='Frequencia', title='Gêneros Mais Frequentes').show()

"""### 3.2. Nota média por gênero"""

genero_score = (
    df_exploded.group_by('Genres')
    .agg(pl.col('Score').mean().alias('Nota Média'))
    .sort('Nota Média', descending=True)
)

px.bar(genero_score.head(15).to_pandas(), x='Genres', y='Nota Média', title='Top 15 Gêneros com Melhores Notas').show()
px.bar(genero_score.tail(15).to_pandas(), x='Genres', y='Nota Média', title='15 Gêneros com Piores Notas').show()

"""### 3.3. Combinações de gêneros mais comuns"""

df_combos = df_clean.filter(pl.col('Genres').list.len() > 1)

combo_freq = (
    df_combos
    .group_by('Genres_combination')
    .agg(pl.count().alias('Frequencia'))
    .sort('Frequencia', descending=True)
)

px.bar(combo_freq.head(15).to_pandas(), x='Genres_combination', y='Frequencia',
       title='🔗 Combinações de Gêneros Mais Comuns (com 2 ou mais gêneros)').show()

"""### 3.4. Estúdios com melhor nota média

"""

df_studios = df_clean.filter(
    (pl.col('Studios').is_not_null()) & (pl.col('Studios') != "None")
)

# Agrupar por estúdio e calcular média e contagem
studio_avg = (
    df_studios
    .group_by('Studios')
    .agg([
        pl.col('Score').mean().alias('Nota Média'),
        pl.count().alias('Quantidade de Animes')
    ])
    .filter(pl.col('Quantidade de Animes') >= 5)
    .sort('Nota Média', descending=True)
)

fig = px.bar(
    studio_avg.head(15).to_pandas(),  # Top 15 estúdios com melhor nota média
    x='Studios',
    y='Nota Média',
    title='🎬 Estúdios com as Melhores Notas Médias (com pelo menos 5 animes)',
    text='Nota Média',
    labels={'Studios': 'Estúdio', 'Nota Média': 'Nota Média'}
)
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig.update_layout(xaxis_tickangle=-45)
fig.show()

""" ### 3.5. Relação entre popularidade e avaliação"""

relacao_popularidade = df_clean.select(['Score', 'Members', 'Genres_combination']).to_pandas()

px.scatter(relacao_popularidade, x='Score', y='Members', color='Genres_combination',
           size='Members', hover_data=['Genres_combination'],
           title='Relação entre Nota e Popularidade por Gênero').show()

"""# 4. Modelo SVM para predição de notas

### 4.1. Filtragem das colunas necessárias
"""

df_clean.columns

df_para_ml = df_clean.select(
    ['MAL_ID','Name', 'Genres', 'Score']
)

df_para_ml_com_membros = df_clean.select(
    ['MAL_ID','Name', 'Genres', 'Score', 'Members']
)

"""### 4.2. One-Hot Encoding nos generos das listas de cada linha

Uso de Machine Learning utilizando a database a fim de validar as transformações realizadas e uso da mesma
"""

def one_hot_encode(df, column_name):
    # Get all unique genres
    all_genres = df[column_name].explode().unique().sort()

    expressions = []
    for genre in all_genres:
        expressions.append(
            pl.col(column_name).list.contains(genre).alias(f"{column_name}_{genre}")
        )

    df = df.with_columns(expressions)
    return df.drop(column_name)

df_para_ml = one_hot_encode(df_para_ml, 'Genres')
df_para_ml = df_para_ml.drop('Name', 'MAL_ID')

df_para_ml_com_membros = one_hot_encode(df_para_ml_com_membros, 'Genres')
df_para_ml_com_membros = df_para_ml_com_membros.drop('Name', 'MAL_ID')

df_para_ml.head(), df_para_ml_com_membros.head()

# download dos dataframes polars em csv
df_para_ml.write_csv('df_para_ml.csv')
df_para_ml_com_membros.write_csv('df_para_ml_com_membros.csv')

"""### 4.3. Função de treinamento e teste

Implementação de modelo de SVM utilizando 10-10-fold para predição da nota baseado em generos, contendo ou não o numero de membros de cada entrada.
"""

from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

def train_and_evaluate_knn(df, n_neighbors=5):
    # Separate features (X) and target (y)
    # Assuming 'Score' is the target variable and the rest are features
    X = df.drop('Score').to_numpy()
    y = df['Score'].to_numpy()

    # Define the number of folds
    n_folds = 10

    # Initialize KFold
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=42)

    # Initialize list to store evaluation scores
    mse_scores = []

    # Loop through each fold
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        # Initialize the KNeighborsRegressor model
        model = KNeighborsRegressor(n_neighbors=n_neighbors)

        # Train the model
        model.fit(X_train, y_train)

        # Predict on the test set
        y_pred = model.predict(X_test)

        # Evaluate the model using Mean Squared Error
        mse = mean_squared_error(y_test, y_pred)
        mse_scores.append(mse)

    # Calculate the average MSE across all folds
    average_mse = np.mean(mse_scores)

    return average_mse, mse_scores

"""### 4.4. Resultados do modelo

4.4.1. Modelo somente com Score e generos
"""

average_mse, mse_scores = train_and_evaluate_knn(df_para_ml)
print("MSE por fold:", mse_scores)
print("Média do erro quadrático médio:", average_mse)

"""4.4.2. Modelo com número de membros"""

average_mse_membros, mse_scores_membros = train_and_evaluate_knn(df_para_ml_com_membros)
print(f"MSE por fold: {mse_scores_membros}")
print(f"Média do erro quadrático médio: {average_mse_membros}")